### PR TITLE
Migrating from new Meteor.Collection to new Mongo.Collection

### PR DESCRIPTION
**Pull request by SDaron**
Small update... Meteor.Collection was renamed Mongo.Collection in Meteor 0.9.1

### CODE REVIEW

**Comment by dburles** [comment]
Thanks @SDaron

**Comment by SDaron** [comment]
Thxs,
actually it was the package collection-hooks who alert me on this, displaying an alert in logs:
```
collection-hooks.js:188 Consider migrating from `new Meteor.Collection` to `new Mongo.Collection` in: function () {

///////////////////////////////////////////////////////////////////////
//                                                                   //
// packages/tmeasday:presence/lib/common.js                          //
//                                                                   //
///////////////////////////////////////////////////////////////////////
                                                                     //
Presences = new Meteor.Collection('presences');                      // 1
// For backwards compatibilty                                        // 2
Meteor.presences = Presences;                                        // 3
                                                                     // 4
Meteor.methods({                                                     // 5
  updatePresence: function(state) {                                  // 6
    check(state, Match.Any);                                         // 7
                                                                     // 8
    var connectionId = this.isSimulation                             // 9
      ? Meteor.connection._lastSessionId                             // 10
      : this.connection.id;                                          // 11
                                                                     // 12
    // Should never happen                                           // 13
    if (! connectionId)                                              // 14
      return;                                                        // 15
                                                                     // 16
    var update = {};                                                 // 17
    update.state = state;                                            // 18
    if (typeof Meteor.userId !== 'undefined' && Meteor.userId())     // 19
      update.userId = Meteor.userId();                               // 20
                                                                     // 21
    Presences.update(connectionId, update);                          // 22
  }                                                                  // 23
});                                                                  // 24
                                                                     // 25
///////////////////////////////////////////////////////////////////////
}
```
As this message is quite long and "polluting" would you consider make a version update in atmosphere?

**Comment by dburles** [comment]
Sorry, totally forgot to publish. Just did now!

**Comment by SDaron** [comment]
That was quick, but you have to add:
```
api.use('mongo', ['client', 'server']);
```
Else an error is now raised:
```
Mongo is not defined
```

**Comment by dburles** [comment]
Ooh, thanks, I just updated it

**Comment by SDaron** [comment]
Ok it work now, thxs for this nice package

**Comment by dburles** [comment]
You're welcome

**Pull request merged**
